#!/bin/sh
if [ ! -f PKGBUILD ]
then
    echo "Change to a directory that has a PKGBUILD file to use this script."
    exit 1
fi

sudo chgrp nobody $(pwd)
sudo chmod g+w $(pwd)
sudo -u nobody makepkg "$@"
